// This file is @generated by prost-build.
/// The request message.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamRequest {
    /// The data to stream
    #[prost(string, tag = "1")]
    pub data: ::prost::alloc::string::String,
}
/// The response message.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamReply {
    /// The streamed message
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod streaming_test_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// The streaming test service definition.
    #[derive(Debug, Clone)]
    pub struct StreamingTestClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> StreamingTestClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> StreamingTestClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            StreamingTestClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Server streaming RPC
        pub async fn server_stream(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::StreamReply>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/test_ws.v1.StreamingTest/ServerStream",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("test_ws.v1.StreamingTest", "ServerStream"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Client streaming RPC
        pub async fn client_stream(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::StreamRequest>,
        ) -> std::result::Result<tonic::Response<super::StreamReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/test_ws.v1.StreamingTest/ClientStream",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("test_ws.v1.StreamingTest", "ClientStream"));
            self.inner.client_streaming(req, path, codec).await
        }
        /// Bidirectional streaming RPC
        pub async fn bidi_stream(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::StreamReply>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/test_ws.v1.StreamingTest/BidiStream",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("test_ws.v1.StreamingTest", "BidiStream"));
            self.inner.streaming(req, path, codec).await
        }
        /// Unary RPC - should NOT generate WS handler
        pub async fn unary_call(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamRequest>,
        ) -> std::result::Result<tonic::Response<super::StreamReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/test_ws.v1.StreamingTest/UnaryCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("test_ws.v1.StreamingTest", "UnaryCall"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod streaming_test_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with StreamingTestServer.
    #[async_trait]
    pub trait StreamingTest: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the ServerStream method.
        type ServerStreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::StreamReply, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Server streaming RPC
        async fn server_stream(
            &self,
            request: tonic::Request<super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::ServerStreamStream>,
            tonic::Status,
        >;
        /// Client streaming RPC
        async fn client_stream(
            &self,
            request: tonic::Request<tonic::Streaming<super::StreamRequest>>,
        ) -> std::result::Result<tonic::Response<super::StreamReply>, tonic::Status>;
        /// Server streaming response type for the BidiStream method.
        type BidiStreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::StreamReply, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Bidirectional streaming RPC
        async fn bidi_stream(
            &self,
            request: tonic::Request<tonic::Streaming<super::StreamRequest>>,
        ) -> std::result::Result<tonic::Response<Self::BidiStreamStream>, tonic::Status>;
        /// Unary RPC - should NOT generate WS handler
        async fn unary_call(
            &self,
            request: tonic::Request<super::StreamRequest>,
        ) -> std::result::Result<tonic::Response<super::StreamReply>, tonic::Status>;
    }
    /// The streaming test service definition.
    #[derive(Debug)]
    pub struct StreamingTestServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> StreamingTestServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for StreamingTestServer<T>
    where
        T: StreamingTest,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/test_ws.v1.StreamingTest/ServerStream" => {
                    #[allow(non_camel_case_types)]
                    struct ServerStreamSvc<T: StreamingTest>(pub Arc<T>);
                    impl<
                        T: StreamingTest,
                    > tonic::server::ServerStreamingService<super::StreamRequest>
                    for ServerStreamSvc<T> {
                        type Response = super::StreamReply;
                        type ResponseStream = T::ServerStreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StreamRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StreamingTest>::server_stream(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ServerStreamSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/test_ws.v1.StreamingTest/ClientStream" => {
                    #[allow(non_camel_case_types)]
                    struct ClientStreamSvc<T: StreamingTest>(pub Arc<T>);
                    impl<
                        T: StreamingTest,
                    > tonic::server::ClientStreamingService<super::StreamRequest>
                    for ClientStreamSvc<T> {
                        type Response = super::StreamReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::StreamRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StreamingTest>::client_stream(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ClientStreamSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.client_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/test_ws.v1.StreamingTest/BidiStream" => {
                    #[allow(non_camel_case_types)]
                    struct BidiStreamSvc<T: StreamingTest>(pub Arc<T>);
                    impl<
                        T: StreamingTest,
                    > tonic::server::StreamingService<super::StreamRequest>
                    for BidiStreamSvc<T> {
                        type Response = super::StreamReply;
                        type ResponseStream = T::BidiStreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::StreamRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StreamingTest>::bidi_stream(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BidiStreamSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/test_ws.v1.StreamingTest/UnaryCall" => {
                    #[allow(non_camel_case_types)]
                    struct UnaryCallSvc<T: StreamingTest>(pub Arc<T>);
                    impl<
                        T: StreamingTest,
                    > tonic::server::UnaryService<super::StreamRequest>
                    for UnaryCallSvc<T> {
                        type Response = super::StreamReply;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StreamRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StreamingTest>::unary_call(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnaryCallSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for StreamingTestServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "test_ws.v1.StreamingTest";
    impl<T> tonic::server::NamedService for StreamingTestServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// Generated axum handlers and router.
pub mod streaming_test_axum {
    #![allow(unused_imports)]
    use std::sync::Arc;
    use axum::Json;
    use axum::body::Body;
    use axum::extract::{Path, Query, State};
    use axum_extra::json_lines::JsonLines;
    use axum::extract::WebSocketUpgrade;
    use axum::response::Response;
    use axum::routing::{any, get, post, put, delete, patch};
    use axum::Router;
    use super::streaming_test_server::StreamingTest as _;
    /// Server streaming RPC
    pub async fn server_stream(
        State(state__): State<crate::StreamingTest>,
        headers__: http::HeaderMap,
        extensions__: http::Extensions,
        req__: Json<super::StreamRequest>,
    ) -> http::Response<Body> {
        let req__ = tonic2axum::make_request(headers__, extensions__, req__.0);
        tonic2axum::make_stream_response(state__.server_stream(req__).await)
    }
    /// Client streaming RPC
    pub async fn client_stream(
        State(state__): State<crate::StreamingTest>,
        headers__: http::HeaderMap,
        extensions__: http::Extensions,
        req__: JsonLines<super::StreamRequest>,
    ) -> http::Response<Body> {
        let req__ = tonic2axum::make_stream_request(headers__, extensions__, req__);
        tonic2axum::make_response(state__.client_stream(req__).await)
    }
    /// Bidirectional streaming RPC
    pub async fn bidi_stream(
        State(state__): State<crate::StreamingTest>,
        headers__: http::HeaderMap,
        extensions__: http::Extensions,
        req__: JsonLines<super::StreamRequest>,
    ) -> http::Response<Body> {
        let req__ = tonic2axum::make_stream_request(headers__, extensions__, req__);
        tonic2axum::make_stream_response(state__.bidi_stream(req__).await)
    }
    /// Unary RPC - should NOT generate WS handler
    pub async fn unary_call(
        State(state__): State<crate::StreamingTest>,
        headers__: http::HeaderMap,
        extensions__: http::Extensions,
        req__: Json<super::StreamRequest>,
    ) -> http::Response<Body> {
        let req__ = tonic2axum::make_request(headers__, extensions__, req__.0);
        tonic2axum::make_response(state__.unary_call(req__).await)
    }
    /// Server streaming RPC
    pub async fn server_stream_ws(
        State((state__, protobuf__)): State<(crate::StreamingTest, bool)>,
        ws_upgrade__: WebSocketUpgrade,
        headers__: http::HeaderMap,
        extensions__: http::Extensions,
    ) -> Response {
        tonic2axum::upgrade_to_ws(
                ws_upgrade__,
                headers__,
                extensions__,
                protobuf__,
                |headers__, extensions__, stream, sink, protobuf__| async move {
                    match tonic2axum::make_ws_request(headers__, extensions__, stream)
                        .await
                    {
                        Some(request) => {
                            let response = state__.server_stream(request).await;
                            tonic2axum::process_ws_stream_response(
                                    response,
                                    sink,
                                    protobuf__,
                                )
                                .await;
                        }
                        None => {
                            tonic2axum::close_ws(
                                    sink,
                                    tonic::Status::aborted("No request received"),
                                )
                                .await;
                        }
                    }
                },
            )
            .await
    }
    /// Client streaming RPC
    pub async fn client_stream_ws(
        State((state__, protobuf__)): State<(crate::StreamingTest, bool)>,
        ws_upgrade__: WebSocketUpgrade,
        headers__: http::HeaderMap,
        extensions__: http::Extensions,
    ) -> Response {
        tonic2axum::upgrade_to_ws(
                ws_upgrade__,
                headers__,
                extensions__,
                protobuf__,
                |headers__, extensions__, stream, sink, protobuf__| async move {
                    let request = tonic2axum::make_ws_stream_request(
                        headers__,
                        extensions__,
                        stream,
                    );
                    let response = state__.client_stream(request).await;
                    tonic2axum::process_ws_response(response, sink, protobuf__).await;
                },
            )
            .await
    }
    /// Bidirectional streaming RPC
    pub async fn bidi_stream_ws(
        State((state__, protobuf__)): State<(crate::StreamingTest, bool)>,
        ws_upgrade__: WebSocketUpgrade,
        headers__: http::HeaderMap,
        extensions__: http::Extensions,
    ) -> Response {
        tonic2axum::upgrade_to_ws(
                ws_upgrade__,
                headers__,
                extensions__,
                protobuf__,
                |headers__, extensions__, stream, sink, protobuf__| async move {
                    let request = tonic2axum::make_ws_stream_request(
                        headers__,
                        extensions__,
                        stream,
                    );
                    let response = state__.bidi_stream(request).await;
                    tonic2axum::process_ws_stream_response(response, sink, protobuf__)
                        .await;
                },
            )
            .await
    }
    /// Axum router for the StreamingTest service
    pub fn make_router(state: crate::StreamingTest) -> Router {
        let ws_proto = Router::new()
            .route("/stream/server/ws/proto", any(server_stream_ws))
            .route("/stream/client/ws/proto", any(client_stream_ws))
            .route("/stream/bidi/ws/proto", any(bidi_stream_ws))
            .with_state((state.clone(), true));
        let ws_json = Router::new()
            .route("/stream/server/ws/json", any(server_stream_ws))
            .route("/stream/client/ws/json", any(client_stream_ws))
            .route("/stream/bidi/ws/json", any(bidi_stream_ws))
            .with_state((state.clone(), false));
        Router::new()
            .route("/stream/server", post(server_stream))
            .route("/stream/client", post(client_stream))
            .route("/stream/bidi", post(bidi_stream))
            .route("/stream/unary", post(unary_call))
            .with_state(state)
            .merge(ws_proto)
            .merge(ws_json)
    }
}
